In [21]:
import numpy as np
import pandas as pd

In [2]:
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go

In [30]:
data = pd.read_csv('/Users/apple/NBA-player-data-dash-plotly/2012-18_playerBoxScore.csv',
                            parse_dates=['gmDate'])

In [31]:
data.dtypes

gmDate        datetime64[ns]
gmTime                object
seasTyp               object
playLNm               object
playFNm               object
teamAbbr              object
teamConf              object
teamDiv               object
teamLoc               object
teamRslt              object
teamDayOff             int64
offLNm1               object
offFNm1               object
offLNm2               object
offFNm2               object
offLNm3               object
offFNm3               object
playDispNm            object
playStat              object
playMin                int64
playPos               object
playHeight             int64
playWeight             int64
playBDate             object
playPTS                int64
playAST                int64
playTO                 int64
playSTL                int64
playBLK                int64
playPF                 int64
playFGA                int64
playFGM                int64
playFG%              float64
play2PA                int64
play2PM                int64
play2P%              float64
play3PA                int64
play3PM                int64
play3P%              float64
playFTA                int64
playFTM                int64
playFT%              float64
playORB                int64
playDRB                int64
playTRB                int64
opptAbbr              object
opptConf              object
opptDiv               object
opptLoc               object
opptRslt              object
opptDayOff             int64
dtype: object

### columns 
gmDate

teamRslt

playDispNm

playMin

playPTS

playAST

playTO

playSTL

playBLK

playPF

In [34]:
data_player = data.loc[:, ['gmDate', 'teamRslt', 'playDispNm', 'playMin', 'playPTS', 'playAST', 'playTO', 'playSTL', 'playBLK', 'playPF']]
data_player.head()

,gmDate,teamRslt,playDispNm,playMin,playPTS,playAST,playTO,playSTL,playBLK,playPF
0,2012-10-30,Loss,A.J. Price,29,7,6,1,0,0,1
1,2012-10-30,Loss,Trevor Ariza,25,9,4,0,3,2,0
2,2012-10-30,Loss,Emeka Okafor,25,10,0,1,0,4,1
3,2012-10-30,Loss,Bradley Beal,22,8,3,2,1,0,1
4,2012-10-30,Loss,Trevor Booker,17,4,1,4,1,1,4

In [35]:
data_price = data[(data['playDispNm'].isin(['A.J. Price']))]

In [20]:
go.Scatter(go.Scatter(
            x= data_price.gmDate,
            y= data_price.playPTS,
            mode='lines'))

Scatter({
    'mode': 'lines',
    'x': array(['2012-10-30', '2012-11-03', '2012-11-07', '2012-11-09', '2012-11-10',
                '2012-11-13', '2012-11-14', '2012-11-17', '2012-11-19', '2012-11-21',
                '2012-11-24', '2012-11-26', '2012-11-28', '2012-11-30', '2012-12-04',
                '2012-12-07', '2012-12-08', '2013-01-07', '2013-01-12', '2013-01-14',
                '2013-01-16', '2013-01-18', '2013-01-19', '2013-01-21', '2013-01-23',
                '2013-01-25', '2013-01-26', '2013-01-28', '2013-01-30', '2013-02-01',
                '2013-02-02', '2013-02-04', '2013-02-06', '2013-02-08', '2013-02-11',
                '2013-02-13', '2013-02-19', '2013-02-22', '2013-02-23', '2013-02-25',
                '2013-02-27', '2013-03-03', '2013-03-06', '2013-03-08', '2013-03-09',
                '2013-03-12', '2013-03-29', '2013-03-31', '2013-04-02', '2013-04-03',
                '2013-04-06', '2013-04-07', '2013-04-09', '2013-04-10', '2013-04-12',
                '2013-04-15', '2013-04-17', '2013-11-06', '2013-11-10', '2013-11-13',
                '2013-11-16', '2013-11-22', '2013-11-23', '2013-12-01', '2013-12-07',
                '2013-12-10', '2013-12-20', '2013-12-27', '2013-12-28', '2014-01-01',
                '2014-01-06', '2014-01-10', '2014-01-12', '2014-01-17', '2014-01-24',
                '2014-01-25', '2014-02-01', '2014-02-04', '2014-02-05', '2014-02-10',
                '2014-02-12', '2014-02-19', '2014-02-22', '2014-02-23', '2014-03-05',
                '2014-11-07', '2014-11-08', '2014-11-10', '2014-11-12', '2014-11-14',
                '2014-11-15', '2014-11-19', '2014-11-22', '2014-11-24', '2014-11-26',
                '2014-12-04', '2014-12-08', '2014-12-11', '2014-12-17', '2014-12-23',
                '2014-12-26', '2014-12-28', '2014-12-30', '2014-12-31', '2015-01-04',
                '2015-01-05', '2015-03-21', '2015-03-22', '2015-03-25', '2015-03-27',
                '2015-03-30'], dtype=object),
    'y': array([ 7,  8, 15, 12, 12,  6, 11,  8,  8, 14,  2, 11,  3,  8, 14,  6,  0,  4,
                16, 18,  7,  6,  7,  4, 10,  6,  7,  2,  2,  6,  5,  5,  2,  6,  4,  0,
                 4, 12,  5, 12,  9,  2,  3, 10,  4,  3,  4,  6, 13,  5,  4, 15, 11, 23,
                 6,  4, 24,  0,  2,  0,  3,  2,  0,  0,  0,  5,  0,  0,  0,  0,  9,  3,
                 4,  0,  2,  0,  0,  0,  3,  2,  4,  0,  0,  5,  0,  5,  9, 22,  7, 14,
                21,  7,  6,  3, 11,  0,  0,  0,  0,  0,  0,  2,  4,  4,  6,  6,  2,  2,
                 0,  0,  2])
})

In [22]:
dictlist = []
unique_list = data.playDispNm.unique()
unique_list.sort()
for title in unique_list:
    dictlist.append({'value': title, 'label': title})

In [27]:
list(dictlist[0].values())

['A.J. Hammons', 'A.J. Hammons']

In [36]:
data_player.gmDate.min

<bound method Series.min of 0        2012-10-30
1        2012-10-30
2        2012-10-30
3        2012-10-30
4        2012-10-30
5        2012-10-30
6        2012-10-30
7        2012-10-30
8        2012-10-30
9        2012-10-30
10       2012-10-30
11       2012-10-30
12       2012-10-30
13       2012-10-30
14       2012-10-30
15       2012-10-30
16       2012-10-30
17       2012-10-30
18       2012-10-30
19       2012-10-30
20       2012-10-30
21       2012-10-30
22       2012-10-30
23       2012-10-30
24       2012-10-30
25       2012-10-30
26       2012-10-30
27       2012-10-30
28       2012-10-30
29       2012-10-30
            ...
155683   2018-04-11
155684   2018-04-11
155685   2018-04-11
155686   2018-04-11
155687   2018-04-11
155688   2018-04-11
155689   2018-04-11
155690   2018-04-11
155691   2018-04-11
155692   2018-04-11
155693   2018-04-11
155694   2018-04-11
155695   2018-04-11
155696   2018-04-11
155697   2018-04-11
155698   2018-04-11
155699   2018-04-11
155700   2018-04-11
155701   2018-04-11
155702   2018-04-11
155703   2018-04-11
155704   2018-04-11
155705   2018-04-11
155706   2018-04-11
155707   2018-04-11
155708   2018-04-11
155709   2018-04-11
155710   2018-04-11
155711   2018-04-11
155712   2018-04-11
Name: gmDate, Length: 155713, dtype: datetime64[ns]>

In [51]:
data.tail(1).values

array([[Timestamp('2018-04-11 00:00:00'), '10:30', 'Regular', 'Cooley',
        'Jack', 'SAC', 'West', 'Pacific', 'Home', 'Win', 2, 'Tiven',
        'Josh', 'Orr', 'J.T.', 'Foster', 'Scott', 'Jack Cooley', 'Bench',
        18, 'PF', 81, 246, '1991-04-04', 10, 1, 2, 0, 0, 3, 4, 1, 0.25,
        4, 1, 0.25, 0, 0, 0.0, 10, 8, 0.8, 1, 3, 4, 'HOU', 'West',
        'Southwest', 'Away', 'Loss', 1]], dtype=object)

In [56]:
data[(data['playDispNm']=='Jack Cooley') & (data['gmDate'].dt.year==2015)]

,gmDate,gmTime,seasTyp,playLNm,playFNm,teamAbbr,teamConf,teamDiv,teamLoc,teamRslt,...,playFT%,playORB,playDRB,playTRB,opptAbbr,opptConf,opptDiv,opptLoc,opptRslt,opptDayOff
69717,2015-02-27,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,0,0,0,DEN,West,Northwest,Home,Loss,2
72477,2015-03-16,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.0,0,3,3,CHA,East,Southeast,Away,Loss,3
72853,2015-03-18,22:30,Regular,Cooley,Jack,UTA,West,Northwest,Home,Loss,...,0.0,0,0,0,WAS,East,Southeast,Away,Win,2
72921,2015-03-19,22:30,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,0,0,0,LAL,West,Pacific,Home,Loss,3
73282,2015-03-21,22:30,Regular,Cooley,Jack,UTA,West,Northwest,Away,Loss,...,1.0,0,0,0,GS,West,Pacific,Home,Win,1
73995,2015-03-25,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Loss,...,0.0,0,0,0,POR,West,Northwest,Away,Win,1
74305,2015-03-27,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Loss,...,0.0,0,0,0,DEN,West,Northwest,Home,Win,2
74422,2015-03-28,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.0,1,1,2,OKC,West,Northwest,Away,Loss,3
74734,2015-03-30,20:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,0,1,1,MIN,West,Northwest,Home,Loss,1
75067,2015-04-01,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.5,1,1,2,DEN,West,Northwest,Away,Loss,4
75707,2015-04-05,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,2,3,5,SAC,West,Pacific,Home,Loss,2
76126,2015-04-08,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.0,0,1,1,SAC,West,Pacific,Away,Loss,1
76450,2015-04-10,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Loss,...,0.0,0,0,0,MEM,West,Southwest,Away,Win,2
76557,2015-04-11,22:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,2,1,3,POR,West,Northwest,Home,Loss,2
76956,2015-04-13,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.4,1,1,2,DAL,West,Southwest,Away,Loss,1
77139,2015-04-15,20:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Loss,...,0.4,3,3,6,HOU,West,Southwest,Home,Win,2

In [57]:
data[data['playDispNm']=='Jack Cooley']

,gmDate,gmTime,seasTyp,playLNm,playFNm,teamAbbr,teamConf,teamDiv,teamLoc,teamRslt,...,playFT%,playORB,playDRB,playTRB,opptAbbr,opptConf,opptDiv,opptLoc,opptRslt,opptDayOff
69717,2015-02-27,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,0,0,0,DEN,West,Northwest,Home,Loss,2
72477,2015-03-16,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.0,0,3,3,CHA,East,Southeast,Away,Loss,3
72853,2015-03-18,22:30,Regular,Cooley,Jack,UTA,West,Northwest,Home,Loss,...,0.0,0,0,0,WAS,East,Southeast,Away,Win,2
72921,2015-03-19,22:30,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,0,0,0,LAL,West,Pacific,Home,Loss,3
73282,2015-03-21,22:30,Regular,Cooley,Jack,UTA,West,Northwest,Away,Loss,...,1.0,0,0,0,GS,West,Pacific,Home,Win,1
73995,2015-03-25,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Loss,...,0.0,0,0,0,POR,West,Northwest,Away,Win,1
74305,2015-03-27,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Loss,...,0.0,0,0,0,DEN,West,Northwest,Home,Win,2
74422,2015-03-28,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.0,1,1,2,OKC,West,Northwest,Away,Loss,3
74734,2015-03-30,20:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,0,1,1,MIN,West,Northwest,Home,Loss,1
75067,2015-04-01,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.5,1,1,2,DEN,West,Northwest,Away,Loss,4
75707,2015-04-05,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,2,3,5,SAC,West,Pacific,Home,Loss,2
76126,2015-04-08,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.0,0,1,1,SAC,West,Pacific,Away,Loss,1
76450,2015-04-10,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Loss,...,0.0,0,0,0,MEM,West,Southwest,Away,Win,2
76557,2015-04-11,22:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Win,...,0.0,2,1,3,POR,West,Northwest,Home,Loss,2
76956,2015-04-13,21:00,Regular,Cooley,Jack,UTA,West,Northwest,Home,Win,...,0.4,1,1,2,DAL,West,Southwest,Away,Loss,1
77139,2015-04-15,20:00,Regular,Cooley,Jack,UTA,West,Northwest,Away,Loss,...,0.4,3,3,6,HOU,West,Southwest,Home,Win,2
134635,2017-11-18,10:00,Regular,Cooley,Jack,SAC,West,Pacific,Away,Loss,...,1.0,0,1,1,POR,West,Northwest,Home,Win,1
150527,2018-03-09,10:00,Regular,Cooley,Jack,SAC,West,Pacific,Home,Win,...,0.0,3,0,3,ORL,East,Southeast,Away,Loss,1
153836,2018-03-31,10:00,Regular,Cooley,Jack,SAC,West,Pacific,Home,Loss,...,1.0,3,4,7,GS,West,Pacific,Away,Win,1
154103,2018-04-01,09:30,Regular,Cooley,Jack,SAC,West,Pacific,Away,Win,...,0.5,3,5,8,LAL,West,Pacific,Home,Loss,1
154799,2018-04-06,08:00,Regular,Cooley,Jack,SAC,West,Pacific,Away,Win,...,0.0,3,2,5,MEM,West,Southwest,Home,Loss,1
155264,2018-04-09,08:30,Regular,Cooley,Jack,SAC,West,Pacific,Away,Loss,...,0.5,1,1,2,SA,West,Southwest,Home,Win,1
155712,2018-04-11,10:30,Regular,Cooley,Jack,SAC,West,Pacific,Home,Win,...,0.8,1,3,4,HOU,West,Southwest,Away,Loss,1

In [81]:
data[['gmDate']].set_index('gmDate').resample('A-OCT')

ValueError: Lengths must match

In [86]:
data[['gmDate']].apply(lambda x: x in pd.date_range('2014-04-02',periods=10,freq='D',normalize=True))

gmDate    False
dtype: bool

In [91]:
start_date='2018-03-02'
data[['gmDate']] > start_date

        gmDate
0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
...        ...
155683    True
155684    True
155685    True
155686    True
155687    True
155688    True
155689    True
155690    True
155691    True
155692    True
155693    True
155694    True
155695    True
155696    True
155697    True
155698    True
155699    True
155700    True
155701    True
155702    True
155703    True
155704    True
155705    True
155706    True
155707    True
155708    True
155709    True
155710    True
155711    True
155712    True

[155713 rows x 1 columns]